### ISSUE TITLE
Add ability to override table names

### ISSUE THREAD

**Issue by ludriv** [maximilienGilet/notification-bundle#17]

**Comment by nreynis** [comment]
I think this is linked to: https://github.com/maximilienGilet/notification-bundle/issues/18

Doctrine already offer the possibility to override/customize table names with custom naming strategies

**Comment by nreynis** [comment]
I use this as a temporary patch to restore Doctrine default behaviour

```php
<?php

namespace AppBundle\ORM\Mapping;

use Doctrine\Common\EventSubscriber;
use Doctrine\Common\EventArgs;
use Doctrine\ORM\Mapping\NamingStrategy;
use Mgilet\NotificationBundle\Entity\NotifiableEntity;
use Mgilet\NotificationBundle\Entity\NotifiableNotification;
use Mgilet\NotificationBundle\Entity\Notification;

class NotificationPatch implements EventSubscriber
{
    /**
     * @var NamingStrategy
     */
    protected $namingStrategy;

    public function __construct(NamingStrategy $strategy)
    {
        $this->namingStrategy = $strategy;
    }

    public function getSubscribedEvents(): array
    {
        return ['loadClassMetadata'];
    }

    /**
     * Restore naming strategy in mgilet/notification-bundle entities
     */
    public function loadClassMetadata(EventArgs $eventArgs): void
    {
        $metadata = $eventArgs->getClassMetadata();

        if($metadata->name === NotifiableEntity::class
                || $metadata->name === NotifiableNotification::class
                || $metadata->name === Notification::class){
            $metadata->table['name'] = $this->namingStrategy->classToTableName($metadata->name);
        }
    }
}
```

And in service.yml
```
services:
    AppBundle\ORM\Mapping\NotificationPatch:
        class: AppBundle\ORM\Mapping\NotificationPatch
        # pass whatever strategy you were using in the first place
        arguments: ['@doctrine.orm.naming_strategy.underscore']
        tags:
            - { name: doctrine.event_subscriber, connection: default }
```
