### ISSUE TITLE
I have difficulty to make notification system in symfony 4

### ISSUE THREAD

**Issue by khaliltr** [maximilienGilet/notification-bundle#57]
I have Difficulty to add notifications in symfony

I use this bundle https://github.com/maximilienGilet/notification-bundle

I have followed the doc, but i have encountered difficulty

THis what i have added in controller ( add annonce)
```
class TestController extends AbstractController
{

    /**
     * @Route("/", name="test")
     */
    public function index(Request $request)
    {..
if ($form->isSubmitted() && $form->isValid()) {
        $manager = $this->get('mgilet.notification');
        $notif = $manager->createNotification('Nouveau candidat !');
        $notif->setMessage('X a entré un candidat');
        $notif->setLink('http://symfony.com/');
        $manager->addNotification(array($this->getUser()), $notif, true);

        return $this->redirectToRoute('index');
}
```
And this what i have added in twig {{ mgilet_notification_render(app.user) }}

But after adding annonce i see this error

**_Service "mgilet.notification" not found: even though it exists in the app's container, the container inside "App\Controller\TestController" is a smaller service locator that only knows about the "doctrine", "form.factory", "http_kernel", "parameter_bag", "request_stack", "router", "security.authorization_checker", "security.csrf.token_manager", "security.token_storage", "serializer", "session", "templating" and "twig" services. Try using dependency injection instead._**

Maybee i haven't know how to show notifications in twig,
the documentation is not very clear for beginners

**Comment by maximilienGilet** [comment]
Hi @khaliltr thanks for using the bundle :)

With Symfony 4 you have to specify services to use in your controller, the usage of the global container doesn't work anymore.

This might help you : https://symfony.com/doc/current/service_container.html

**Comment by khaliltr** [comment]
I haven't understand, what i need to add in services.yml?

**Comment by khaliltr** [comment]
Please i need help, 

I have added this in controller
public function controllerFunction(Mgilet\NotificationBundle\Manager\NotificationManager $manager)
{
    $notif = $manager->createNotification('New Test');
    $notif->setMessage('Test');
    $notif->setLink('http://symfony.com/');
    $manager->addNotification(array($this->getUser()), $notif, true);

    return $this->redirectToRoute('index');
}


But $notif is not added in database and in twig i see only the word "notifications" when i add  {{ mgilet_notification_render(app.user) }}

**Comment by maximilienGilet** [comment]
@khaliltr Have you updated your database schema ?

**Comment by khaliltr** [comment]
yes i have notifiable_entity, notifiable_notification, and notification ,

I have added this in service.yaml
```
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            Mgilet\NotificationBundle\Manager\NotificationManager: '@mgilet.notification'
```

and

```
public function controllerFunction(Mgilet\NotificationBundle\Manager\NotificationManager $manager)
{
$notif = $manager->createNotification('New Test');
$notif->setMessage('Test');
$notif->setLink('http://symfony.com/');
$manager->addNotification(array($this->getUser()), $notif, true);

return $this->redirectToRoute('index');
}
```

the results : nothing in twig only the word "notifications" and nothing in database
