### ISSUE TITLE
Missing config at installation : "Unknown Entity namespace" error.

### ISSUE THREAD

**Issue by RomainCoupez** [maximilienGilet/notification-bundle#66]
Hi everyone ! 
Just to let you know that with the last version of symfony (4.3.3), i had to add thoses lines of config in my doctrine.yaml for make the bundle works ! 
```
orm: 
     entity_managers: 
           mappings: 
                MgiletNotificationBundle:
                    is_bundle: true
                    type: annotation
                    prefix: 'Mgilet\NotificationBundle\Entity'
                    alias: MgiletNotificationBundle
```

In case of someone want to use the bundle and have the "Unknown Entity namespace alias 'MgiletNotificationBundle'." error ! 
Thanks for your work, still really great 👍

**Comment by nwafo** [comment]
merçi bcp . cette erreur ma bcp tracasser l'esprit

**Comment by jcgriebel** [comment]
Depuis la mise en place dans symfony 4.4 du pool cache pour doctrine la solution marche en mode Dev et pas en mode Prod
Je n'ai pas trouver de solution autre que supprimer dans config/packages/prod le fichier doctrine.yaml.
Si quelqu'un à une solution je suis preneur.

**Comment by jcgriebel** [comment]
J'ai trouvé une solution.
dans config/packages/prod/doctrine.yaml j'ai mis.

```
doctrine:
    orm:
        auto_generate_proxy_classes: false
        entity_managers:
            Default:
                metadata_cache_driver:
                    type: pool
                    pool: doctrine.system_cache_pool
                query_cache_driver:
                    type: pool
                    pool: doctrine.system_cache_pool
                result_cache_driver:
                    type: pool
                    pool: doctrine.result_cache_pool

framework:
    cache:
        pools:
            doctrine.result_cache_pool:
                adapter: cache.app
            doctrine.system_cache_pool:
                adapter: cache.system
```
