### ISSUE TITLE
How to use this in Symfony 4.4

### ISSUE THREAD

**Issue by easternmayurt** [maximilienGilet/notification-bundle#70]
Hi @marcelglaeser @avramcosmin @emulienfou @matthieumota @Viperoo @4ssil @maximilienGilet I am new in Symfony and trying to use this notification bundle in my project but didn't get proper configurations steps for Symfony 4.4 can anyone in the group please help me. #HELP REQUIRED

**Comment by easternmayurt** [comment]
![Screenshot from 2019-12-10 20-14-34](https://user-images.githubusercontent.com/39591253/70539485-ce125980-1b89-11ea-9596-d9fe21df3cd2.png)
Now I got this error, can anyone of you please help me.
I have changed in the Entity added  
```
@Notifiable(name="user")
```
bind notification bundle inside services.yaml
```
bind:
            Mgilet\NotificationBundle\Manager\NotificationManager : "@mgilet.notification"
mgilet.twig_extension:
        class: Mgilet\NotificationBundle\Twig\NotificationExtension
        arguments: ['@mgilet.notification', '@security.token_storage', '@twig', '@router']
```
Inside controller added following below-mentioned function
```
public function sendNotification(\Mgilet\NotificationBundle\Manager\NotificationManager $manager)
    {
        $notif = $manager->createNotification('New Test');
        $notif->setMessage('Test');
        $notif->setLink('http://symfony.com/');
        $manager->addNotification([$this->getUser()], $notif, true);

        return $this->redirectToRoute('currencies');
    }
```
What else is missing here ?
